# Generated by Django 6.0.3 on 2026-03-04 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_count', models.PositiveSmallIntegerField(default=0)),
                ('message_template', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='customer.customers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['user', 'name'], name='customer_cu_user_id_b5d7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['user', 'phone'], name='customer_cu_user_id_1960d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('user', 'phone')},
        ),
        migrations.AddIndex(
            model_name='due',
            index=models.Index(fields=['user', 'status', 'due_at'], name='customer_du_user_id_1a426b_idx'),
        ),
        migrations.AddIndex(
            model_name='due',
            index=models.Index(fields=['customer', 'status', 'due_at'], name='customer_du_custome_e6202c_idx'),
        ),
    ]
